title: BBX TABZ
description: various beats & breaks, transcribed as beatbox tablature
theme: jekyll-theme-minimal
permalink: pretty
collections:
  songs:
    output: true
  breaks:
    output: true
  ltbb:
    output: true
