title: BBX TBZ
description: various beats & breaks, transcribed as tablature for beatboxing
theme: jekyll-theme-minimal
permalink: pretty
github:
  is_project_page: false
collections:
  songs:
    output: true
  breaks:
    output: true
  ltbb:
    output: true
